package com.example.data.services

import com.example.domain.model.Characters
import com.example.domain.model.Comics
import com.example.domain.model.Wrapper
import retrofit2.http.GET
import retrofit2.http.Path
import retrofit2.http.Query

interface MarvelApi {

    /**
     * Find all marvel characters
     * @param ts time stamp to hash auth
     * @param apikey generated by developer.marvel.com
     * @param hash Mds combination auth
     */
    @GET("v1/public/characters")
    suspend fun listCharacters(
        @Query("ts") ts: String,
        @Query("apikey") apikey: String,
        @Query("hash") hash: String,
        @Query("limit") limit: String = "20",
        @Query("offset") offset: String = "0"
    ) : Wrapper<Characters>

    /**
     * Find all comics by id from characters
     * @param characterId Id from character
     */
    @GET("v1/public/characters/{characterId}/comics")
    suspend fun listComics(
        @Path("characterId") characterId: String,
        @Query("ts") ts: String,
        @Query("apikey") apikey: String,
        @Query("hash") hash: String
    ): Wrapper<Comics>

}